### ISSUE TITLE
Rework the jbrowse_to_existing tool

### ISSUE THREAD

**Issue by abretaud** [galaxy-genome-annotation/galaxy-tools#1]
As discussed in galaxyproject/tools-iuc/pull/994

**Comment by abretaud** [comment]
ping @erasche

I think it is ready for a new review now if you have time, here's what I did:
- renamed the tool to something I hope more understandable + added an iframe as output which is indeed much nicer.
- I'll see later if I can add a default value (relative path to jbrowse if it works) for $GALAXY_JBROWSE_SHARED_URL in https://github.com/erasche/docker-galaxy-annotation/blob/master/Dockerfile
- now instead of adding 1 new jbrowse dataset to what's already in the DATA_DIR, I replace what's there by x new jbrowse datasets. It lowers the risk of ID collision, and allow to use a cleaner <configile>
- I left the unique_id because I think some of the end users will want it anyway, but I put it in advanced section with a warning. Is it ok for you?

**Comment by erasche** [comment]
sure do, apologies for delays.

> and allow to use a cleaner 

nice! I need to implement this somehow for the current Apollo - JBrowse integration, right now all the old folders just pile up. (But maybe this is a "feature", keeps historical views of data? Dunno)

Sure @ unique_id. Will review in IUC repo. Thanks for adding the tools here.

**Comment by abretaud** [comment]
Oh I forgot to finish my phrase :smile: I meant something like "and allow to use a cleaner configfile", or something like this
Anyway, I'm not sure either if piling up datasets is a feature, a little less safe, but don't know if it could be useful in real life
