### ISSUE TITLE
Missing --common and --abbr in tripal organism_add_organism.xml

### ISSUE THREAD

**Issue by loraine-gueguen** [galaxy-genome-annotation/galaxy-tools#26]
Running the tool in the Galaxy container, I have had this issue:
```
Fatal error: Matched on Error
Usage: tripaille organism add_organism [OPTIONS] GENUS SPECIES

Error: Got unexpected extra arguments (ccrispus C. crispus)
```
Indeed, in the xml, "--common" and "--abbr" are missing in the command line in the xml file.
Surprisingly, there is no error in the Travis tests: https://travis-ci.org/galaxy-genome-annotation/galaxy-tools/jobs/411801601.  I am not sure why.

**Comment by abretaud** [comment]
Thanks for the issue and the fix!
The tests are ok because they are not real tests (yet), they just check that tripaille tries and fails to connect to a non-existing tripal instance. Some day we should run a tripal/chado/apollo dockers and run real tests
