### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by erasche** [galaxy-genome-annotation/galaxy-tools#3]

**Comment by bgruening** [comment]
MIT?

**Comment by erasche** [comment]
Up to @abretaud, just noticed this was missing when I added the badges to the site.

**Comment by abretaud** [comment]
Done :)
I also added the tripal tools from https://github.com/galaxyproject/tools-iuc/pull/1083. I'd like to add some dynamic options as for apollo tools, so it's probably better to put them here.
(I'm busy preparing for a conf next week, things should be quieter after that for me (I hope))

**Comment by erasche** [comment]
Dynamic like these? https://github.com/galaxy-genome-annotation/galaxy-apollo/blob/master/macros.xml#L62

someday soon (tm), I'll merge that repo with this galaxy-tools repo. Then we can have everything in one place which will be nice.

**Comment by abretaud** [comment]
> Dynamic like these? https://github.com/galaxy-genome-annotation/galaxy-apollo/blob/master/macros.xml#L62

Yep, like this! I know dynamic_options are not *good*, but it would make the tools muuuch easier to use

Great work for the new website, it was needed indeed!
Cheers

**Comment by erasche** [comment]
By adding those, I reduced my helpdesk emails for this issue from ~50/year to ZERO. All from people typoing their genome's name and not understanding why it wasn't working.

They will never take away my dynamic_options.
