### ISSUE TITLE
Plans to update to Apollo latest version?

### ISSUE THREAD

**Issue by monicacecilia** [galaxy-genome-annotation/galaxy-tools#34]
Hello friends at Galaxy Tools,

I have a team of collaborators who are interested in using your marvelous, handy work and they are interested in learning whether your team has any plans in motion for updating the tool to the Apollo latest version. See https://github.com/GMOD/Apollo/releases/latest

Looking forward to hearing the good news! 

Thank you!

**Comment by erasche** [comment]
So the tools should work with any version of apollo, unless the API has changed radically? I don't think we require a specific version of apollo anywhere with the Galaxy tools.

Are there some tools that are missing or non-functional?

In the [dockerized-gmod-deployment](https://github.com/galaxy-genome-annotation/dockerized-gmod-deployment), we definitely need to update, but that's been a lower priority.

**Comment by monicacecilia** [comment]
Thanks @erasche! I think the version they instantiated originated from an aging fork - and what is visible to me from their installation is a version of Apollo labeled as SNAPSHOT-2.1.1.  I'll dig more on their end before bugging you guys further. cheers!

**Comment by abretaud** [comment]
I've been playing with apollo 2.3 these days: the galaxy tools are working fine, at least for what I've tested.
You just need to use the latest version of the jbrowse tool from the toolshed (1.16.2) (but older version will probably work too)

**Comment by erasche** [comment]
This seems resolved, please re-open @monicacecilia  if there's any more information from their side regarding potential issues on our end :)
