### ISSUE TITLE
Prefixing common names

### ISSUE THREAD

**Issue by hexylena** [galaxy-genome-annotation/galaxy-tools#46]
In create or update we say "avoid shared common names"

What would you think about prefixing them, @abretaud? Maybe with their user ID or so? This would prevent the possibility of duplicates? We could auto-strip it in the UI, maybe, to present a cleaner list to users.

**Comment by abretaud** [comment]
Ah yep good idea, it would be better with multiple users indeed!
But yes I'd need auto-stripping in ui for my bipaa genomes (=deployed by a single account, and users don't need to know who)

**Comment by erasche** [comment]
Ah ok, interesting. We could prefix with apollo user ID or so.

It'd be easy to strip it in the list in the galaxy side, but it would be present in the apollo side. Would that be OK for you?

**Comment by abretaud** [comment]
ah, I was thinking about stripping on the apollo side, that's what I'd need :) But it shouldn't be too hard to patch apollo I guess, with a nice option in the conf to enable it or not

**Comment by erasche** [comment]
Ahh hmm. I guess we could hide it behind an env var flag in webapollo.py, you would leave it off and we (eu) could turn it on?

**Comment by abretaud** [comment]
Ah yes! I'd use it in my future apollo.genouest.org I think

**Comment by abretaud** [comment]
So I've implemented something like that in https://github.com/galaxy-genome-annotation/galaxy-tools/pull/44/commits/cf6f0613a4f6548d957f35d59c43287ff2ee6d51 (#44)
If GALAXY_APOLLO_ORG_SUFFIX env var is set, it will add the owner user email as a suffix like this: `Test org (test@bx.psu.edu)`
I made a test with using userid instead, but commented it as I found it confusing in the UI
I also did not remove the suffix in dynamic options as it could be problematic if someone has access to orgs with the same name from 2 different users -> no way to tell which one you alter if the suffix is not there

what do you think @erasche? (if you have time of course!)

**Comment by erasche** [comment]
Hej @abretaud, my only concern is the email address is probably not optimal for EU users, and I would rather not edit the tool XML in production. What about:

```
GALAXY_APOLLO_ORG_SUFFIX= # anything ⇒ disabled
GALAXY_APOLLO_ORG_SUFFIX=email 
GALAXY_APOLLO_ORG_SUFFIX=id
```

or so? And then standardising on `Test org (test@bx.psu.edu)` and `Test org (gx123)` as the suffixes? 

Sounds good @ not auto-removing the suffix. My original thought was removing only if it matched your user ID/email, so you'd have `Test org` and `Test org (some-other-person)` but, that seems too complex, fine to have them show on all :)

**Comment by abretaud** [comment]
Thanks :) I've made the changes
I'm also finishing to add support for remote upload of orgs

**Comment by hexylena** [comment]
:tada: !!!
